#!/usr/bin/env bash
# Usage: script/md2html
# Generates HTML5 version of résumé from Markdown version.

pandoc -f markdown -t html5 -o resume.html -s -M pagetitle:'Résumé' --email-obfuscation=references -c styles.css -c "https://fonts.googleapis.com/css?family=Source+Sans+Pro" resume.md
